In [1]:
# Importing the required libraries
import cv2
import face_recognition
import os
from datetime import datetime
import numpy as np

In [2]:
# Helper function to read an image given the path to that image
def read_image(image_file_path):
    
#     Using the inbuilt library function to read the image
    image = face_recognition.load_image_file(image_file_path)
    
#     Recolouring the read image RGB standard
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    
#     Returning the read image
    return image

In [3]:
# Helper function to create the encoding vector for the input image
def encode_image(image):
    
#     Using the inbuilt library function to create the encoding vector
    encoded_image = face_recognition.face_encodings(image)[0]
    
#     Returning the encoding vector
    return encoded_image

In [4]:
# Helper function to determine the location of the face in the input image
def get_face_location(image):
    
#     Using the inbuilt library function to determine the boxed location of the face in the input image
    face_location = face_recognition.face_locations(image)[0]
    
#     Returning the boxed location of the face in the input image
    return face_location

In [5]:
# Helper function to encode all the existing images in the database
def encode_stored_images(base_directory_path):
    
#     Creating an empty list of all encodings of all images in the database
    encoded_stored_images = []
    
#     Traversing all images in the database
    for image_file_name in os.listdir(base_directory_path):
        
#         Getting the exact file path for each image
        image_file_path = base_directory_path + '/' + image_file_name
        
#         Reading each image file into an image object
        image = read_image(image_file_path)
    
#         Creating the encoding vector of each image
        encoded_image = encode_image(image)
    
#         Adding the current encoding vector to the list of all encodings
        encoded_stored_images.append(encoded_image)
    
#     Returning the list of all encodings of all images in the database
    return encoded_stored_images

In [6]:
# Helper function to get the name of person which most closely resembles the facial features of
# the input subject 
def get_most_similar_person(subject_image, encoded_stored_images, people_list):
    
#     Creating the encoding vector of the input subject image
    encoded_subject_image = encode_image(subject_image)
    
#     Creating the array of face_similarity_distances in which each element is the facial similarity
#     distance between the input subject and the ith person in the database
    face_similarity_distances = face_recognition.face_distance(encoded_stored_images,
                                                               encoded_subject_image)
    
#     Getting the index of the person who most closely resembles the input subject
    most_similar_face_index = np.argmin(face_similarity_distances)
    
#     Getting the name of the person who most closely resembles the input subject
    most_similar_person = people_list[most_similar_face_index]
    
#     Returning the name of the person who most closely resembles the input subject
    return most_similar_person

In [7]:
# Helper function to get the list of the names of all the people in the database
def get_all_people_list(base_directory_path):
    
#     Creating an empty list of the names of all the people in the database 
    people_list = []
    
#     Traversing each image file in the database
    for image_file_name in os.listdir(base_directory_path):
        
#         Getting the name of the person from the file
        person_name = image_file_name.split('.')[0]
    
#         Adding the name of the person to the list of the names of all the people in the database
        people_list.append(person_name)
    
#   Returning the list of the names of all the people in the database  
    return people_list

In [8]:
# Defining the path to the folder to be treated as the databse of stored images
# Accordingly change this path to where all the stored images are located in your machine
stored_images_base_directory_path = 'C:\Work\Machine Learning projects\Face Recognition system\
Family Database'

# Getting the list of the names of all the people in the database
people_list = get_all_people_list(stored_images_base_directory_path)

# Creating the list of encoding vectors of all the images present in the database
encoded_stored_images = encode_stored_images(stored_images_base_directory_path)

In [10]:
# Setting the parameters and source (webcam of the native machine) for the opencv functionality to
# take input from the webcam of the native machine
source = cv2.VideoCapture(0)

# Running the application till the user wants
while(True):
    
#     Reading the input image from the source 
    success, current_face_frame = source.read()
    
#     The read code above throws an exception if no face is found 
    try:
        face_location = get_face_location(current_face_frame)
    except:
        print('Face not found')
    
#     Getting the name of the person that most closely resembles the input subject
    most_similar_person_name = get_most_similar_person(current_face_frame, encoded_stored_images,
                                                       people_list)
    
#     Boxing the face detected by Opencv for more interactive experience
    cv2.rectangle(current_face_frame, (face_location[3], face_location[0]),
                  (face_location[1], face_location[2]), (255,0,255),2)
    
#     Displaying the name of the person that most closely resembles the input subject
    cv2.putText(current_face_frame, most_similar_person_name, (50, 50), cv2.FONT_HERSHEY_COMPLEX,
                1,(0,0,255), 2)
    
#     Displaying the results in real time on the screen
    cv2.imshow('LIVE', current_face_frame)
    
#     Get an input from the keyboard from the user
    break_key = cv2.cv2.waitKey(1)
    
#     Defining the specific key that stops the application
    if(break_key == 27):
        break

# Cleaning up after the application has stopped
cv2.destroyAllWindows()
source.release()

[0.39083419 0.38646792 0.72575502 0.64611899] 1
[0.40305509 0.39324979 0.74013552 0.64980647] 1
[0.40511913 0.4018274  0.72133419 0.66124454] 1
[0.41353959 0.3641193  0.75445334 0.65497616] 1
Face not found


IndexError: list index out of range